### ISSUE TITLE
Time control ?

### ISSUE THREAD

**Issue by winwisely99** [zonble/flutter_turtle#1]
I want to be able to draw things over time do it plays back drawing the lines on the screen one at a time.

In the demo it shows them finished as if the turtle has already walked the path.

Does this make sense ?

**Comment by zonble** [comment]
I just wrap Flutter's CustomPaint right now. It means, I just use a canvas to draw a graph and I did not do anything about animation. If we want to make with widget animated, I still have a lot to do.

**Comment by zonble** [comment]
Please try version 0.3.0. I added a new class `AnimatedTurtleView`.
